### 1.5 넘파이

#### 1.5.2 넘파이 배열 생성하기

In [1]:
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)

type(x)

[1. 2. 3.]


numpy.ndarray

#### 1.5.3 넘파이의 산술 연산

x, y의 원소 수가 같다면 산술 연산은 각 원소에 대해 행해진다 (element - wise). 
수가 다르면 오류가 발생한다.

넘파이 배열은 수치 하나 (스칼라값)의 조합으로도 계산할 수 있는데 이 기능을 원소별로 한 번씩 수행되는 브로드캐스트라고 한다.

In [4]:
y = np.array([2.0, 4.0, 6.0])

print(x + y)
print(x - y)
print(x * y)
print(x / y)

print(x / 2.0)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]
[0.5 1.  1.5]


#### 1.5.4 넘파이의 N차원 배열

행렬의 형상 (배열 각 차원의 크기 - 원소 수)은 shape으로,
행렬의 담긴 원소의 자료형은 dtpye으로 알 수 있다.

형상이 같은 행렬 역시 브로드캐스트 기능이 작동된다.

1차원 배열, 2차원 배열, 3차원 배열 처럼 원하는 차수의 배열을 만들 수 있다.

In [7]:
A = np.array([[1, 2], [3, 4]])

print(A, A.shape, A.dtype)

[[1 2]
 [3 4]] (2, 2) int32


In [11]:
B = np.array([[3, 0], [0, 6]])

print(A + B)
print(A * B)
print(A * 10)

[[ 4  2]
 [ 3 10]]
[[ 3  0]
 [ 0 24]]
[[10 20]
 [30 40]]


#### 1.5.5 브로드캐스트

형상이 다른 배열끼리도 계산이 가능하다.
2 * 2 행렬에 스칼라 10을 곱하면 10이 2 * 2로 확대되어 연산이 이뤄지는데 이를 브로드캐스트라 한다.

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

print(A*B) # B가 A와 똑같은 형상으로 변형되어 원소별 연산이 이루어진다.

print(B*A)

[[10 40]
 [30 80]]
[[10 40]
 [30 80]]


#### 1.5.6 원소 접근

인덱스를 배열로 지정해 한 번에 여러 원소에 접근할 수도 있다.

In [16]:
x = np.array([[51, 55], [14, 19], [0, 4]])

print(x[0], x[0][1]) # 0행, (0,1) 위치 원소

for row in x: print(row)
    
x = x.flatten() # x를 1차원 배열로 변환 (평탄화)
print(x)

print(x[np.array([0, 2, 4])]) # 인덱스가 0, 2, 4인 원소 얻기


[51 55] 55
[51 55]
[14 19]
[0 4]
[51 55 14 19  0  4]
[51 14  0]
