### 3.3 다차원 배열의 계산

#### 3.3.1 다차원 배열

사실상 다차원 배열의 기본도 숫자의 집합이라 할 수 있다.

In [2]:
import numpy as np

A = np.array([1, 2, 3, 4])
print(A)

print(np.ndim(A)) # 배열의 차원 수

print(A.shape) # 배열의 형상 - 튜플로 반환

print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [3]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

print(np.ndim(B))

print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


#### 3.3.2 행렬의 곱

행렬 곱은 왼쪽 행렬의 행과 오른쪽 행렬의 열을 원소별로 곱하고 그 값들을 더해서 계산한다. 그리고 그 값들을 모두 더해서 계산하여 새로운 다차원 배열의 원소가 된다.

np.dot()은 스칼라 곱을 뜻하여 입력이 1차원 배열이면 벡터를, 2차원 배열이면 행렬 곱을 계산한다.
피연산자의 순서가 다르면 결과도 다르다.

In [5]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(A.shape, B.shape)
print(np.dot(A, B))
print(np.dot(B, A))

(2, 2) (2, 2)
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


그럼 형상이 다른 행렬의 곱도 가능할까?

In [6]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2], [3,4], [5,6]])

print(A.shape, B.shape)
print(np.dot(A, B))

(2, 3) (3, 2)
[[22 28]
 [49 64]]


이 때 행렬의 형상에 주의 해야하는데, 행렬 A의 1번째 차원의 원소 수 (열 수)와 행렬 B의 0번째 차원의 원소 수 (행 수)가 같아야 한다.
아니면 차원의 원소수가 다르다는 에러를 띄운다.

In [7]:
C = np.array([[1,2], [3,4]])

print(np.dot(A, C))

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

다차원 배열을 곱하려면 두 행렬의 대응하는 차원의 원소 수를 일치시켜야 한다.
3 X 2 행렬 A와, 2 X 3 행렬 B를 곱해 3 X 4 행렬 C를 만드는 예다.
결과는 A의 행, B의 열 수가 된다.

A가 2차원, B가 1차원 일때도 대응하는 차원의 원소 수를 일치시켜라는 원칙은 똑같이 적용된다.

3 X 2 -> A
2 X (1)-> B
3 -> C

In [8]:
A = np.array([[1,2], [3,4], [5,6]])
B = np.array([7, 8])

print(A.shape, B.shape)
print(np.dot(A, B))

(3, 2) (2,)
[23 53 83]


#### 3.3.3 신경망에서의 행렬 곱

이제 넘파이 행렬을 써서 신경망을 구현해보자.
편향과 활성화 함수는 생략하고 가중치만 갖는다고 해보자.

In [9]:
X = np.array([1, 2])
print(X.shape)

w = np.array([[1, 3, 5], [2, 4, 6]])
print(w.shape)

Y = np.dot(X, w)
print(Y)

(2,)
(2, 3)
[ 5 11 17]
